name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7, 'ruby', 'head', 'jruby']
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libzmq3-dev libsodium-dev
      - name: Run tests
        run: bundle exec rspec
